--[[
  DaDaPush Public API
 
  DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 
  The version of the OpenAPI document: v1
  Contact: contacts@dadapush.com
  Generated by: https://openapi-generator.tech
]]

-- message_push_response class
local message_push_response = {}
local message_push_response_mt = {
	__name = "message_push_response";
	__index = message_push_response;
}

local function cast_message_push_response(t)
	return setmetatable(t, message_push_response_mt)
end

local function new_message_push_response(message_id)
	return cast_message_push_response({
		["messageId"] = message_id;
	})
end

return {
	cast = cast_message_push_response;
	new = new_message_push_response;
}
