--[[
  DaDaPush Public API
 
  DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 
  The version of the OpenAPI document: v1
  Contact: contacts@dadapush.com
  Generated by: https://openapi-generator.tech
]]

-- message_object class
local message_object = {}
local message_object_mt = {
	__name = "message_object";
	__index = message_object;
}

local function cast_message_object(t)
	return setmetatable(t, message_object_mt)
end

local function new_message_object(actions, channel_name, content, created_at, id, title)
	return cast_message_object({
		["actions"] = actions;
		["channelName"] = channel_name;
		["content"] = content;
		["createdAt"] = created_at;
		["id"] = id;
		["title"] = title;
	})
end

return {
	cast = cast_message_object;
	new = new_message_object;
}
