--[[
  DaDaPush Public API
 
  DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 
  The version of the OpenAPI document: v1
  Contact: contacts@dadapush.com
  Generated by: https://openapi-generator.tech
]]

-- message_push_request class
local message_push_request = {}
local message_push_request_mt = {
	__name = "message_push_request";
	__index = message_push_request;
}

local function cast_message_push_request(t)
	return setmetatable(t, message_push_request_mt)
end

local function new_message_push_request(actions, content, need_push, title)
	return cast_message_push_request({
		["actions"] = actions;
		["content"] = content;
		["needPush"] = need_push;
		["title"] = title;
	})
end

return {
	cast = cast_message_push_request;
	new = new_message_push_request;
}
