--[[
  DaDaPush Public API
 
  DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 
  The version of the OpenAPI document: v1
  Contact: contacts@dadapush.com
  Generated by: https://openapi-generator.tech
]]

-- page_response_of_message_object class
local page_response_of_message_object = {}
local page_response_of_message_object_mt = {
	__name = "page_response_of_message_object";
	__index = page_response_of_message_object;
}

local function cast_page_response_of_message_object(t)
	return setmetatable(t, page_response_of_message_object_mt)
end

local function new_page_response_of_message_object(content, total_elements, total_pages)
	return cast_page_response_of_message_object({
		["content"] = content;
		["totalElements"] = total_elements;
		["totalPages"] = total_pages;
	})
end

return {
	cast = cast_page_response_of_message_object;
	new = new_page_response_of_message_object;
}
