--[[
  DaDaPush Public API
 
  DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 
  The version of the OpenAPI document: v1
  Contact: contacts@dadapush.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for dadapush_client.model.message_push_request
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("message_push_request", function()
  local dadapush_client_message_push_request = require "dadapush_client.model.message_push_request"

  -- unit tests for the property 'actions'
  describe("property actions test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'content'
  describe("property content test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'need_push'
  describe("property need_push test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

  -- unit tests for the property 'title'
  describe("property title test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
