--[[
  DaDaPush Public API
 
  DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 
  The version of the OpenAPI document: v1
  Contact: contacts@dadapush.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for dadapush_client.model.message_push_response
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("message_push_response", function()
  local dadapush_client_message_push_response = require "dadapush_client.model.message_push_response"

  -- unit tests for the property 'message_id'
  describe("property message_id test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
